name: "Apply on Merged PR"

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        id: init
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: terraform init
        working-directory: src/terraform

      - name: Terraform Apply
        id: init
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          TF_VAR_project: crdant-net
          TF_VAR_region: us-west-1
          TF_VAR_gcp_key: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: terraform apply -auto-approve=yes
        working-directory: src/terraform
